---
- name: Ngnix Installation and Start & Enable
  hosts: all
  gather_facts: yes
  tasks: 
    - name: Install EPEL-RELEASE
      yum: 
        name: epel-release
        state: latest

    - name: Install Nginx
      yum:
        name: nginx
        state: latest

    - name: Start & Enable nginx 
      systemd: 
        name: nginx
        state: started
        enabled: yes
