---
- name: Ngnix Installation and Start & Enable
  hosts: all
  gather_facts: yes
  tasks: 
    - name: Install EPEL-RELEASE
      yum: 
        name: epel-release
        state: latest

    - name: Install Nginx on CentOS
      yum:
        name: nginx
        state: latest
        when: ansible_distribution == "CentOS"

    - name: Install Nginx on Ubuntu
      apt:
        name: nginx
        state: latest
        when: ansible_distribution == "Ubuntu"

    - name: Start & Enable nginx 
      systemd: 
        name: nginx
        state: started
        enabled: yes
